version: '3.7'
services:

  web:
    volumes:
      - ./digster_api:/app/digster_api/
  pgadmin:
    container_name: pgadmin_digster
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-digster:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
volumes:
  pgadmin-digster: null
