"""Add_genres_styles

Revision ID: 052feb61bd36
Revises: 42bc9ec37b9a
Create Date: 2022-04-04 15:38:10.129742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052feb61bd36'
down_revision = '42bc9ec37b9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_album_genres_album_id'), 'album_genres', ['album_id'], unique=False)
    op.create_index(op.f('ix_album_genres_genre_id'), 'album_genres', ['genre_id'], unique=False)
    op.create_index(op.f('ix_album_genres_id'), 'album_genres', ['id'], unique=False)
    op.create_table('album_styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('style', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_album_styles_album_id'), 'album_styles', ['album_id'], unique=False)
    op.create_index(op.f('ix_album_styles_id'), 'album_styles', ['id'], unique=False)
    op.create_index(op.f('ix_album_styles_style'), 'album_styles', ['style'], unique=False)
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_genre'), 'genres', ['genre'], unique=False)
    op.create_index(op.f('ix_genres_id'), 'genres', ['id'], unique=False)
    op.create_table('styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_styles_id'), 'styles', ['id'], unique=False)
    op.create_index(op.f('ix_styles_style'), 'styles', ['style'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_styles_style'), table_name='styles')
    op.drop_index(op.f('ix_styles_id'), table_name='styles')
    op.drop_table('styles')
    op.drop_index(op.f('ix_genres_id'), table_name='genres')
    op.drop_index(op.f('ix_genres_genre'), table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_album_styles_style'), table_name='album_styles')
    op.drop_index(op.f('ix_album_styles_id'), table_name='album_styles')
    op.drop_index(op.f('ix_album_styles_album_id'), table_name='album_styles')
    op.drop_table('album_styles')
    op.drop_index(op.f('ix_album_genres_id'), table_name='album_genres')
    op.drop_index(op.f('ix_album_genres_genre_id'), table_name='album_genres')
    op.drop_index(op.f('ix_album_genres_album_id'), table_name='album_genres')
    op.drop_table('album_genres')
    # ### end Alembic commands ###
