"""add_album

Revision ID: 2a65a738f7be
Revises: 50e466fde1c2
Create Date: 2021-12-14 00:32:07.505399

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2a65a738f7be"
down_revision = "50e466fde1c2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("spotify_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("genres", sa.String(), nullable=True),
        sa.Column("followers", sa.Integer(), nullable=True),
        sa.Column("popularity", sa.Integer(), nullable=True),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_artists_id"), "artists", ["id"], unique=False)
    op.create_index(op.f("ix_artists_name"), "artists", ["name"], unique=False)
    op.create_index(
        op.f("ix_artists_spotify_id"), "artists", ["spotify_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_artists_spotify_id"), table_name="artists")
    op.drop_index(op.f("ix_artists_name"), table_name="artists")
    op.drop_index(op.f("ix_artists_id"), table_name="artists")
    op.drop_table("artists")
    # ### end Alembic commands ###
