"""test_makefile_args

Revision ID: 2fafc7035ee6
Revises: 7a346ab4b075
Create Date: 2021-12-11 12:25:29.162462

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2fafc7035ee6"
down_revision = "7a346ab4b075"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "age_2")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("age_2", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
