"""db-init

Revision ID: 31a8b6b835b2
Revises: 
Create Date: 2022-05-22 01:21:40.048698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "31a8b6b835b2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
