"""add_listens

Revision ID: 382273a8dd01
Revises: 80e487e50212
Create Date: 2021-12-11 20:34:16.396485

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "382273a8dd01"
down_revision = "80e487e50212"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "listens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.TIMESTAMP(), nullable=True),
        sa.Column("song_id", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_listens_id"), "listens", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_listens_id"), table_name="listens")
    op.drop_table("listens")
    # ### end Alembic commands ###
