"""db-init

Revision ID: 4174e8ef1d63
Revises: 
Create Date: 2022-10-20 10:55:15.651131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4174e8ef1d63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_album_genres_album_id'), 'album_genres', ['album_id'], unique=False)
    op.create_index(op.f('ix_album_genres_genre_id'), 'album_genres', ['genre_id'], unique=False)
    op.create_index(op.f('ix_album_genres_id'), 'album_genres', ['id'], unique=False)
    op.create_table('album_styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('style_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_album_styles_album_id'), 'album_styles', ['album_id'], unique=False)
    op.create_index(op.f('ix_album_styles_id'), 'album_styles', ['id'], unique=False)
    op.create_index(op.f('ix_album_styles_style_id'), 'album_styles', ['style_id'], unique=False)
    op.create_table('albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_id', sa.String(), nullable=True),
    sa.Column('artist_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('upc_id', sa.String(), nullable=True),
    sa.Column('genres', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.Column('total_tracks', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('primary_color', sa.String(), nullable=True),
    sa.Column('secondary_color', sa.String(), nullable=True),
    sa.Column('tertiary_color', sa.String(), nullable=True),
    sa.Column('fourth_color', sa.String(), nullable=True),
    sa.Column('fifth_color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_albums_artist_id'), 'albums', ['artist_id'], unique=False)
    op.create_index(op.f('ix_albums_id'), 'albums', ['id'], unique=False)
    op.create_index(op.f('ix_albums_spotify_id'), 'albums', ['spotify_id'], unique=False)
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('genres', sa.String(), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artists_id'), 'artists', ['id'], unique=False)
    op.create_index(op.f('ix_artists_name'), 'artists', ['name'], unique=False)
    op.create_index(op.f('ix_artists_spotify_id'), 'artists', ['spotify_id'], unique=False)
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('following_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_following', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follows_follower_id'), 'follows', ['follower_id'], unique=False)
    op.create_index(op.f('ix_follows_following_id'), 'follows', ['following_id'], unique=False)
    op.create_index(op.f('ix_follows_id'), 'follows', ['id'], unique=False)
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_genre'), 'genres', ['genre'], unique=False)
    op.create_index(op.f('ix_genres_id'), 'genres', ['id'], unique=False)
    op.create_table('listens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listened_at', sa.DateTime(), nullable=True),
    sa.Column('track_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listens_id'), 'listens', ['id'], unique=False)
    op.create_table('styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_styles_id'), 'styles', ['id'], unique=False)
    op.create_index(op.f('ix_styles_style'), 'styles', ['style'], unique=False)
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('album_id', sa.String(), nullable=True),
    sa.Column('danceability', sa.Float(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('key', sa.Float(), nullable=True),
    sa.Column('loudness', sa.Float(), nullable=True),
    sa.Column('mode', sa.Float(), nullable=True),
    sa.Column('speechiness', sa.Float(), nullable=True),
    sa.Column('acousticness', sa.Float(), nullable=True),
    sa.Column('instrumentalness', sa.Float(), nullable=True),
    sa.Column('liveness', sa.Float(), nullable=True),
    sa.Column('valence', sa.Float(), nullable=True),
    sa.Column('tempo', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracks_id'), 'tracks', ['id'], unique=False)
    op.create_index(op.f('ix_tracks_spotify_id'), 'tracks', ['spotify_id'], unique=False)
    op.create_table('user_albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_spotify_id', sa.Integer(), nullable=True),
    sa.Column('album_spotify_id', sa.String(), nullable=True),
    sa.Column('added_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_albums_album_spotify_id'), 'user_albums', ['album_spotify_id'], unique=False)
    op.create_index(op.f('ix_user_albums_id'), 'user_albums', ['id'], unique=False)
    op.create_index(op.f('ix_user_albums_user_spotify_id'), 'user_albums', ['user_spotify_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('has_allowed_fetching', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_albums_user_spotify_id'), table_name='user_albums')
    op.drop_index(op.f('ix_user_albums_id'), table_name='user_albums')
    op.drop_index(op.f('ix_user_albums_album_spotify_id'), table_name='user_albums')
    op.drop_table('user_albums')
    op.drop_index(op.f('ix_tracks_spotify_id'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_id'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_index(op.f('ix_styles_style'), table_name='styles')
    op.drop_index(op.f('ix_styles_id'), table_name='styles')
    op.drop_table('styles')
    op.drop_index(op.f('ix_listens_id'), table_name='listens')
    op.drop_table('listens')
    op.drop_index(op.f('ix_genres_id'), table_name='genres')
    op.drop_index(op.f('ix_genres_genre'), table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_follows_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_following_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_follower_id'), table_name='follows')
    op.drop_table('follows')
    op.drop_index(op.f('ix_artists_spotify_id'), table_name='artists')
    op.drop_index(op.f('ix_artists_name'), table_name='artists')
    op.drop_index(op.f('ix_artists_id'), table_name='artists')
    op.drop_table('artists')
    op.drop_index(op.f('ix_albums_spotify_id'), table_name='albums')
    op.drop_index(op.f('ix_albums_id'), table_name='albums')
    op.drop_index(op.f('ix_albums_artist_id'), table_name='albums')
    op.drop_table('albums')
    op.drop_index(op.f('ix_album_styles_style_id'), table_name='album_styles')
    op.drop_index(op.f('ix_album_styles_id'), table_name='album_styles')
    op.drop_index(op.f('ix_album_styles_album_id'), table_name='album_styles')
    op.drop_table('album_styles')
    op.drop_index(op.f('ix_album_genres_id'), table_name='album_genres')
    op.drop_index(op.f('ix_album_genres_genre_id'), table_name='album_genres')
    op.drop_index(op.f('ix_album_genres_album_id'), table_name='album_genres')
    op.drop_table('album_genres')
    # ### end Alembic commands ###
