"""add_albums

Revision ID: 50e466fde1c2
Revises: b415f78581b3
Create Date: 2021-12-13 16:58:20.268595

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "50e466fde1c2"
down_revision = "b415f78581b3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "albums",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("spotify_id", sa.String(), nullable=True),
        sa.Column("artist_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("genres", sa.String(), nullable=True),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("popularity", sa.Integer(), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("total_tracks", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_albums_artist_id"), "albums", ["artist_id"], unique=False
    )
    op.create_index(op.f("ix_albums_id"), "albums", ["id"], unique=False)
    op.create_index(
        op.f("ix_albums_spotify_id"), "albums", ["spotify_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_albums_spotify_id"), table_name="albums")
    op.drop_index(op.f("ix_albums_id"), table_name="albums")
    op.drop_index(op.f("ix_albums_artist_id"), table_name="albums")
    op.drop_table("albums")
    # ### end Alembic commands ###
