"""test_makefile_args

Revision ID: 7a346ab4b075
Revises: 7d2059f8f978
Create Date: 2021-12-11 12:23:28.956554

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7a346ab4b075"
down_revision = "7d2059f8f978"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("age_2", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "age_2")
    # ### end Alembic commands ###
