"""test_makefile_args

Revision ID: 7d2059f8f978
Revises: 8c110d784b37
Create Date: 2021-12-11 12:22:57.782856

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7d2059f8f978"
down_revision = "8c110d784b37"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "age_2")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("age_2", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
