"""test

Revision ID: 8c110d784b37
Revises: f67e709b3c53
Create Date: 2021-12-11 12:19:48.571970

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8c110d784b37"
down_revision = "f67e709b3c53"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("age_2", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "age_2")
    # ### end Alembic commands ###
