"""add_settings

Revision ID: 92d6e4e894fa
Revises: 7db569652867
Create Date: 2022-05-16 22:45:31.701824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d6e4e894fa'
down_revision = '7db569652867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_allowed_fetching', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_allowed_fetching')
    # ### end Alembic commands ###
