"""song_id-

Revision ID: a0a158fc0571
Revises: 382273a8dd01
Create Date: 2021-12-12 00:24:35.795480

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a0a158fc0571"
down_revision = "382273a8dd01"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("listens", sa.Column("track_id", sa.String(), nullable=True))
    op.drop_column("listens", "song_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "listens",
        sa.Column("song_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("listens", "track_id")
    # ### end Alembic commands ###
