"""empty message

Revision ID: a3cf474a2448
Revises: 
Create Date: 2024-09-05 15:47:28.411159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3cf474a2448'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_albums_album_id'), 'user_albums', ['album_id'], unique=False)
    op.create_index(op.f('ix_user_albums_id'), 'user_albums', ['id'], unique=False)
    op.create_index(op.f('ix_user_albums_user_id'), 'user_albums', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_albums_user_id'), table_name='user_albums')
    op.drop_index(op.f('ix_user_albums_id'), table_name='user_albums')
    op.drop_index(op.f('ix_user_albums_album_id'), table_name='user_albums')
    op.drop_table('user_albums')
    # ### end Alembic commands ###
