"""Add_genres_styles

Revision ID: a4fc1c447e1f
Revises: 052feb61bd36
Create Date: 2022-04-04 15:45:52.424731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4fc1c447e1f'
down_revision = '052feb61bd36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album_styles', sa.Column('style_id', sa.Integer(), nullable=True))
    op.drop_index('ix_album_styles_style', table_name='album_styles')
    op.create_index(op.f('ix_album_styles_style_id'), 'album_styles', ['style_id'], unique=False)
    op.drop_column('album_styles', 'style')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album_styles', sa.Column('style', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_album_styles_style_id'), table_name='album_styles')
    op.create_index('ix_album_styles_style', 'album_styles', ['style'], unique=False)
    op.drop_column('album_styles', 'style_id')
    # ### end Alembic commands ###
