"""add_secondary

Revision ID: bcc4eef0cfe8
Revises: f52661ccfe13
Create Date: 2022-04-07 20:34:02.015360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc4eef0cfe8'
down_revision = 'f52661ccfe13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('primary_color', sa.String(), nullable=True))
    op.add_column('albums', sa.Column('secondary_color', sa.String(), nullable=True))
    op.drop_column('albums', 'dominant_color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('dominant_color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('albums', 'secondary_color')
    op.drop_column('albums', 'primary_color')
    # ### end Alembic commands ###
