"""change_type_to_datetime

Revision ID: c0a922a4500f
Revises: a0a158fc0571
Create Date: 2021-12-12 00:27:58.363064

"""

# revision identifiers, used by Alembic.
revision = "c0a922a4500f"
down_revision = "a0a158fc0571"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
